import { useEffect, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { PageLayout } from "@/components/how2getrich/PageLayout";
import { DottedSpine } from "@/components/how2getrich/DottedSpine";
import { generateH2GRPlan, getH2GRPlan } from "@/lib/h2gr-plan";
import { Wordmark } from "@/components/how2getrich/Wordmark";

// Inline type + static fallback so this route doesn't pull the
// server-side ideas-generator module (and its `process.env` access)
// into the client bundle. The server function returns the same shape.
type H2GRPlanStep = { day: string; title: string; body: string };
const STATIC_PLAN: H2GRPlanStep[] = [
  { day: "day 1", title: "Choose one boring skill people already pay for", body: "examples: editing, landing pages, thumbnails, ads, automation" },
  { day: "day 2", title: "Pick one specific customer with a painful problem", body: "do not build for everyone" },
  { day: "day 3", title: "Find 20 examples of people already making money this way", body: "steal the pattern, not the product" },
  { day: "day 4", title: "Write the dumbest possible offer", body: '"I will help [person] get [result] without [pain]"' },
  { day: "day 5", title: "Make a one-page site explaining the offer", body: "headline, proof, price, contact button" },
  { day: "day 6", title: "Create one tiny sample result", body: "mockup, demo, before/after, screenshot, short video" },
  { day: "day 7", title: "Send the offer to 25 real people", body: "no ads yet. no logo redesign. talk to humans." },
];

export const Route = createFileRoute("/todo")({
  head: () => ({
    meta: [
      { title: "To Do — how2getrich.online" },
      { name: "description", content: "Your tailored 7-day plan." },
    ],
  }),
  validateSearch: (search: Record<string, unknown>) => ({
    s: typeof search.s === "string" ? search.s : "",
  }),
  component: TodoPlan,
});

/**
 * Screen 2 — the tailored 7-day plan. After the user submits Screen 1
 * they land here. The plan is generated by Claude via the
 * generateH2GRPlan server function (reusing the same Anthropic API
 * pipeline that powers the LaunchFly Blueprint generator) and cached
 * in localStorage so we don't burn tokens regenerating on every
 * navigation.
 *
 * Layout: same chrome as Screen 1 (sidebar + right spine + "More info →")
 * with the plan rendered as a list, and the "Get 365 days →" upsell
 * tucked at the bottom.
 */

function TodoPlan() {
  // session_id from the ?s= query param (or localStorage as a backup,
  // for users who hit /todo directly without coming from /).
  const { s: sessionIdFromUrl } = Route.useSearch();

  // Echo the user's answer back at the top of the plan once we have it.
  const [tellMe, setTellMe] = useState<string>("");
  const [plan, setPlan] = useState<H2GRPlanStep[]>(STATIC_PLAN);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let sessionId = sessionIdFromUrl;
    let input = "";
    try {
      if (!sessionId) sessionId = window.localStorage.getItem("h2gr:sessionId") ?? "";
      input = window.localStorage.getItem("h2gr:tellMeAboutYourself") ?? "";
    } catch {
      /* private mode */
    }
    setTellMe(input);

    // If we have neither a session nor an input, there's nothing to
    // generate — leave the static plan visible.
    if (!sessionId && !input) {
      setLoading(false);
      return;
    }

    let cancelled = false;
    (async () => {
      try {
        // Try the persisted plan first — same session id returns the
        // exact plan we already paid Claude for.
        if (sessionId) {
          const cached = await getH2GRPlan({ data: { sessionId } });
          if (cancelled) return;
          if (cached.ok && Array.isArray(cached.plan)) {
            setPlan(cached.plan);
            if (cached.input) setTellMe(cached.input);
            setLoading(false);
            return;
          }
        }

        // Cache miss → generate + persist. Server handles the Claude
        // call and writes to D1 for future loads.
        const res = await generateH2GRPlan({
          data: { sessionId: sessionId ?? "", input },
        });
        if (cancelled) return;
        if (res.ok && Array.isArray(res.plan)) setPlan(res.plan);
      } catch (err) {
        if (cancelled) return;
        console.error("[todo] plan generation failed", err);
        setError("Couldn't reach the plan generator — showing the default plan.");
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [sessionIdFromUrl]);

  return (
    <PageLayout
      rightRail={loading ? undefined : <RightRailWithMoreInfo />}
    >
      {/* While Claude is generating: brand only (Wordmark) + loader.
          The "To Do:" header, the "based on: ..." echo, and the
          right-rail "More info" are intentionally hidden so the
          waiting screen is clean and obviously a transitional state. */}
      {loading ? (
        <>
          <Wordmark />
          <div
            className="mt-[64px] flex w-full max-w-[420px] flex-col items-center gap-[14px]"
            style={{
              fontFamily:
                '"VT323", "JetBrains Mono", ui-monospace, "SF Mono", monospace',
            }}
          >
            <span className="text-[15px] tracking-wide text-white/70">
              generating your plan…
            </span>
            <div className="h-[3px] w-full overflow-hidden rounded-full bg-white/10">
              <div className="h-full w-[35%] animate-h2gr-loader rounded-full bg-white/85" />
            </div>
          </div>
        </>
      ) : (
        <>
          <Header />

          {error && (
            <p
              className="mt-[12px] text-[14px] text-white/40"
              style={{
                fontFamily:
                  '"VT323", "JetBrains Mono", ui-monospace, "SF Mono", monospace',
              }}
            >
              {error}
            </p>
          )}
          <ol
            className="mt-[28px] flex w-full max-w-[437px] flex-col gap-[16px] text-white/90"
            style={{
              fontFamily:
                '"VT323", "JetBrains Mono", ui-monospace, "SF Mono", monospace',
            }}
          >
            {plan.map((step, i) => (
              <li key={step.day}>
                {/* Whole row is a clickable Link → /todo/{N}?s=…
                    -mx-3 px-3 -my-1 py-1 widens the click hit area
                    beyond the visible text without affecting layout;
                    rounded + hover bg gives obvious cursor feedback. */}
                <Link
                  to="/todo/$day"
                  params={{ day: String(i + 1) }}
                  search={{ s: sessionIdFromUrl }}
                  className="group -mx-3 -my-1 flex cursor-pointer items-baseline gap-[8px] rounded-[4px] px-3 py-1 leading-snug transition hover:bg-white/[0.04]"
                >
                  <span className="w-[44px] shrink-0 text-[13.2px] text-white/55 transition group-hover:text-white/80">
                    {step.day}:
                  </span>
                  <span className="flex-1 text-[13.6px] text-white/90 transition group-hover:text-white group-hover:underline group-hover:decoration-white/40 group-hover:underline-offset-[3px]">
                    {step.title}
                  </span>
                </Link>
              </li>
            ))}
          </ol>
        </>
      )}

      {/* Get 365 days upsell — only appears after the plan loads, so
          we don't show a paywall while users are still waiting for
          their tailored content. */}
      {!loading && (
        <div className="mt-[40px] flex w-full justify-center">
          <Link
            to="/todo/upgrade"
            className="group inline-flex h-[80px] w-[437px] max-w-full items-center justify-center gap-[16px] rounded-[6px] bg-white text-[16px] text-black/80 transition hover:text-black focus:outline-none focus:ring-2 focus:ring-white/40"
            style={{
              fontFamily:
                '"VT323", "JetBrains Mono", ui-monospace, "SF Mono", monospace',
            }}
          >
            <span>Full Plan</span>
            <Arrow className="h-[9px] w-[44px] text-black" />
          </Link>
        </div>
      )}
    </PageLayout>
  );
}

/** "To Do:" header in JetBrains Mono, centered. */
function Header() {
  return (
    <h1
      className="mt-[18px] text-[22px] leading-tight text-white"
      style={{
        fontFamily:
          '"VT323", "JetBrains Mono", ui-monospace, "SF Mono", monospace',
      }}
    >
      To Do:
    </h1>
  );
}

/**
 * Floating right rail: dotted spine + "More info →" mid-height.
 * Anchored to the viewport RIGHT but pulled inward 140-165px so it
 * sits closer to the stage instead of hugging the viewport edge.
 */
export function RightRailWithMoreInfo() {
  return (
    <>
      <DottedSpine className="absolute top-[90px] bottom-[60px] right-[140px] z-10" />
      <div
        className="absolute right-[165px] top-[290px] z-10 flex flex-col items-end gap-[8px] text-white/40"
        style={{
          fontFamily:
            '"VT323", "JetBrains Mono", ui-monospace, "SF Mono", monospace',
        }}
      >
        <span className="text-[20px] leading-none">More info</span>
        <Arrow className="h-[5px] w-[44px] text-white/40" />
      </div>
    </>
  );
}

/** Thin right-pointing arrow — used in the CTA + "More info →". */
export function Arrow({ className = "" }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 63 6"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.2"
      strokeLinecap="square"
      strokeLinejoin="miter"
      className={className}
      aria-hidden
    >
      <path d="M0 3h60" />
      <path d="M57 0l5 3-5 3" fill="currentColor" />
    </svg>
  );
}
