/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIdeasRouteImport } from './routes/app.ideas'
import { Route as AppFounderTypeRouteImport } from './routes/app.founder-type'
import { Route as AppFounderDnaRouteImport } from './routes/app.founder-dna'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppBlueprintRouteImport } from './routes/app.blueprint'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIdeasRoute = AppIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => AppRoute,
} as any)
const AppFounderTypeRoute = AppFounderTypeRouteImport.update({
  id: '/founder-type',
  path: '/founder-type',
  getParentRoute: () => AppRoute,
} as any)
const AppFounderDnaRoute = AppFounderDnaRouteImport.update({
  id: '/founder-dna',
  path: '/founder-dna',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBlueprintRoute = AppBlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/blueprint': typeof AppBlueprintRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/founder-dna': typeof AppFounderDnaRoute
  '/app/founder-type': typeof AppFounderTypeRoute
  '/app/ideas': typeof AppIdeasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/blueprint': typeof AppBlueprintRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/founder-dna': typeof AppFounderDnaRoute
  '/app/founder-type': typeof AppFounderTypeRoute
  '/app/ideas': typeof AppIdeasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/blueprint': typeof AppBlueprintRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/founder-dna': typeof AppFounderDnaRoute
  '/app/founder-type': typeof AppFounderTypeRoute
  '/app/ideas': typeof AppIdeasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/blueprint'
    | '/app/dashboard'
    | '/app/founder-dna'
    | '/app/founder-type'
    | '/app/ideas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/blueprint'
    | '/app/dashboard'
    | '/app/founder-dna'
    | '/app/founder-type'
    | '/app/ideas'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/blueprint'
    | '/app/dashboard'
    | '/app/founder-dna'
    | '/app/founder-type'
    | '/app/ideas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/ideas': {
      id: '/app/ideas'
      path: '/ideas'
      fullPath: '/app/ideas'
      preLoaderRoute: typeof AppIdeasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/founder-type': {
      id: '/app/founder-type'
      path: '/founder-type'
      fullPath: '/app/founder-type'
      preLoaderRoute: typeof AppFounderTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/founder-dna': {
      id: '/app/founder-dna'
      path: '/founder-dna'
      fullPath: '/app/founder-dna'
      preLoaderRoute: typeof AppFounderDnaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/blueprint': {
      id: '/app/blueprint'
      path: '/blueprint'
      fullPath: '/app/blueprint'
      preLoaderRoute: typeof AppBlueprintRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBlueprintRoute: typeof AppBlueprintRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFounderDnaRoute: typeof AppFounderDnaRoute
  AppFounderTypeRoute: typeof AppFounderTypeRoute
  AppIdeasRoute: typeof AppIdeasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBlueprintRoute: AppBlueprintRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFounderDnaRoute: AppFounderDnaRoute,
  AppFounderTypeRoute: AppFounderTypeRoute,
  AppIdeasRoute: AppIdeasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
